from __future__ import annotations

from enum import Enum


class PropState(str, Enum):
    NO_PROP = "NO_PROP"
    CHALLENGE_PHASE = "CHALLENGE_PHASE"
    FUNDED_PRE_PAYOUT = "FUNDED_PRE_PAYOUT"
    FIRST_PAYOUT_RECEIVED = "FIRST_PAYOUT_RECEIVED"
    PROP_FAILED_BEFORE_PAYOUT = "PROP_FAILED_BEFORE_PAYOUT"


class PersonalState(str, Enum):
    PERSONAL_ACTIVE = "PERSONAL_ACTIVE"
    PERSONAL_INSUFFICIENT_FOR_HEDGE = "PERSONAL_INSUFFICIENT_FOR_HEDGE"
    PERSONAL_COVERS_NEXT_CHALLENGE = "PERSONAL_COVERS_NEXT_CHALLENGE"
    PERSONAL_DOES_NOT_COVER_NEXT_CHALLENGE = "PERSONAL_DOES_NOT_COVER_NEXT_CHALLENGE"
    PERSONAL_IGNORED_AFTER_PAYOUT = "PERSONAL_IGNORED_AFTER_PAYOUT"


class CycleState(str, Enum):
    CYCLE_RUNNING = "CYCLE_RUNNING"
    CYCLE_SUCCESS = "CYCLE_SUCCESS"
    CYCLE_RECOVERABLE_FAILURE = "CYCLE_RECOVERABLE_FAILURE"
    CYCLE_UNRECOVERABLE_FAILURE = "CYCLE_UNRECOVERABLE_FAILURE"
    SIMULATION_FINISHED = "SIMULATION_FINISHED"


class PersonalDirection(str, Enum):
    OPPOSITE_PROP = "OPPOSITE_PROP"
    NONE = "NONE"

